name: build_750_addons

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs daily at midnight UTC + 2

jobs:
  build_750_addons:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: 750_addons

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Build Script
      run: |
        npm run init
        npm run clone
        npm run copy
        npm run cleanup

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: auto-update
        title: "Automatic Update"
        commit-message: "Automated changes"
        body: "This PR contains automated changes."
        labels: "auto-merge"
    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash  
